### ISSUE TITLE
move server_dumps directory?

### ISSUE THREAD

**Issue by richardehughes** [jannisborn/paperscraper#44]
Is it possible to point the server_dumps directory somewhere other than ./paperscraper/server_dumps?

**Comment by jannisborn** [comment]
Sure, you can move the server_dumps anywhere and then set up the DB Query class like this:

```py
from paperscraper.xrxiv.xrxiv_query import XRXivQuery

querier = XRXivQuery('server_dumps/chemrxiv_2020-11-10.jsonl')
querier.search_keywords(query, output_filepath='covid19_ai_imaging.jsonl')
```


In case you want to download the dumps directly to a given directory, you can also do that, `{bio,med,chem}rxiv()` has a keyword argument `save_path` that defaults to `./paperscraper/server_dumps`.

Hope this helps



See the README for details
