### ISSUE TITLE
error in  !pip install paperscraper 

### ISSUE THREAD

**Issue by mohammad-gh009** [jannisborn/paperscraper#46]
INFO: pip is looking at multiple versions of requests[security] to determine which version is compatible with other requirements. This could take a while.
Collecting requests[security] (from scholarly==0.5.1->paperscraper)
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
  Using cached requests-2.32.2-py3-none-any.whl (63 kB)
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
  Using cached requests-2.29.0-py3-none-any.whl (62 kB)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
  Using cached requests-2.28.0-py3-none-any.whl (62 kB)
INFO: pip is looking at multiple versions of requests[security] to determine which version is compatible with other requirements. This could take a while.
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
  Using cached requests-2.27.0-py2.py3-none-any.whl (63 kB)
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
  Using cached requests-2.20.1-py2.py3-none-any.whl (57 kB)
  Using cached requests-2.20.0-py2.py3-none-any.whl (60 kB)
  Using cached requests-2.19.1-py2.py3-none-any.whl (91 kB)
  Using cached requests-2.19.0-py2.py3-none-any.whl (91 kB)
  Using cached requests-2.18.4-py2.py3-none-any.whl (88 kB)
  Using cached requests-2.18.3-py2.py3-none-any.whl (88 kB)
  Using cached requests-2.18.2-py2.py3-none-any.whl (88 kB)
  Using cached requests-2.18.1-py2.py3-none-any.whl (88 kB)
  Using cached requests-2.18.0-py2.py3-none-any.whl (563 kB)
  Using cached requests-2.17.3-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.17.2-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.17.1-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.17.0-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.16.5-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.16.4-py2.py3-none-any.whl (87 kB)
  Using cached requests-2.16.3-py2.py3-none-any.whl (86 kB)
  Using cached requests-2.16.2-py2.py3-none-any.whl (86 kB)
  Using cached requests-2.16.1-py2.py3-none-any.whl (85 kB)
  Using cached requests-2.16.0-py2.py3-none-any.whl (85 kB)
  Using cached requests-2.15.1-py2.py3-none-any.whl (558 kB)
  Using cached requests-2.14.2-py2.py3-none-any.whl (560 kB)
  Using cached requests-2.14.1-py2.py3-none-any.whl (559 kB)
  Using cached requests-2.14.0-py2.py3-none-any.whl (559 kB)
  Using cached requests-2.13.0-py2.py3-none-any.whl (584 kB)
  Using cached requests-2.12.5-py2.py3-none-any.whl (576 kB)
  Using cached requests-2.12.4-py2.py3-none-any.whl (576 kB)
  Using cached requests-2.12.3-py2.py3-none-any.whl (575 kB)
  Using cached requests-2.12.2-py2.py3-none-any.whl (575 kB)
  Using cached requests-2.12.1-py2.py3-none-any.whl (574 kB)
  Using cached requests-2.12.0-py2.py3-none-any.whl (574 kB)
  Using cached requests-2.11.1-py2.py3-none-any.whl (514 kB)
  Using cached requests-2.11.0-py2.py3-none-any.whl (514 kB)
  Using cached requests-2.10.0-py2.py3-none-any.whl (506 kB)
  Using cached requests-2.9.2-py2.py3-none-any.whl (502 kB)
  Using cached requests-2.9.1-py2.py3-none-any.whl (501 kB)
  Using cached requests-2.9.0-py2.py3-none-any.whl (500 kB)
  Using cached requests-2.8.1-py2.py3-none-any.whl (497 kB)
  Using cached requests-2.8.0-py2.py3-none-any.whl (476 kB)
  Using cached requests-2.7.0-py2.py3-none-any.whl (470 kB)
  Using cached requests-2.6.2-py2.py3-none-any.whl (470 kB)
  Using cached requests-2.6.1-py2.py3-none-any.whl (469 kB)
  Using cached requests-2.6.0-py2.py3-none-any.whl (469 kB)
  Using cached requests-2.5.3-py2.py3-none-any.whl (468 kB)
  Using cached requests-2.5.2-py2.py3-none-any.whl (474 kB)
  Using cached requests-2.5.1-py2.py3-none-any.whl (464 kB)
  Using cached requests-2.5.0-py2.py3-none-any.whl (464 kB)
  Using cached requests-2.4.3-py2.py3-none-any.whl (459 kB)
  Using cached requests-2.4.2-py2.py3-none-any.whl (459 kB)
  Using cached requests-2.4.1-py2.py3-none-any.whl (458 kB)
  Using cached requests-2.4.0-py2.py3-none-any.whl (457 kB)
WARNING: requests 2.4.0 does not provide the extra 'security'
  Using cached requests-2.3.0-py2.py3-none-any.whl (452 kB)
WARNING: requests 2.3.0 does not provide the extra 'security'
  Using cached requests-2.2.1-py2.py3-none-any.whl (625 kB)
WARNING: requests 2.2.1 does not provide the extra 'security'
  Using cached requests-2.2.0-py2.py3-none-any.whl (623 kB)
WARNING: requests 2.2.0 does not provide the extra 'security'
  Using cached requests-2.1.0-py2.py3-none-any.whl (445 kB)
WARNING: requests 2.1.0 does not provide the extra 'security'
  Using cached requests-2.0.1-py2.py3-none-any.whl (439 kB)
WARNING: requests 2.0.1 does not provide the extra 'security'
  Using cached requests-2.0.0-py2.py3-none-any.whl (391 kB)
WARNING: requests 2.0.0 does not provide the extra 'security'
  Using cached requests-1.2.3.tar.gz (348 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I wanted to install this package on Google Colab using Pip but I faced this error.

**Comment by jannisborn** [comment]
Which python version do you use?

**Comment by mohammad-gh009** [comment]
Python 3.10.12

**Comment by jannisborn** [comment]
Hey @mohammad-gh009,

I had some time this morning and released `paperscraper` 0.2.13 which should fix this issue. The issue did not come from paperscraper itself but it is due to a dependency on an outdated version of `scholarly`. The PR #47 is bumping the scholarly dependency which should circumvent the error with `requests[security]` that you are observing. 

Please try running the notebook again and consider directly installing the latest release (`paperscraper==0.2.13`) if the issue persists

**Comment by mohammad-gh009** [comment]
thanks @jannisborn
