### ISSUE TITLE
How can I scrape entire PubMed?

### ISSUE THREAD

**Issue by sleepingcat4** [jannisborn/paperscraper#51]
I want to download all the pdfs in PubMed. No instructions and docs are available. Can you tell me how it can be done?

**Comment by jannisborn** [comment]
Hi @sleepingcat4 

Ouch that's a though one --  not even sure it's possible. For paperscraper, the only thing you could try is querying with a wildcard. I don't have much hope though, depends on how pymed handles special chars. 

So next step would be to ask in the pymed repo: https://github.com/gijswobben/pymed

Paperscraper builds upon that one

**Comment by sleepingcat4** [comment]
btw I tried downloading med, chem and bio arXiv using your code but it doesn't save the dumps on my machine. Do you know why it's happening?

**Comment by jannisborn** [comment]
Arxiv is not downloadable into a local dump. Regarding BiorXiv and Medrxiv, are you sure ? Have you tried specificing "save_path" argument to a local directory with a shorter time range (eg one day) and checked that it's really not created ?

Also, post error logs if you want help

**Comment by sleepingcat4** [comment]
https://matextract.pub/content/obtaining_data/data_mining.html

is this doc relevant for downloading bioXiv, chemXiv and medXiv? btw can I get the latest dumps with all their full text pdfs? @jannisborn

**Comment by jannisborn** [comment]
This is third party content so I can't say for sure but it seems useful. Doesn't do anything more than the examples in the paper scraper README though I think. 

Regarding PDFs, yes you can use "save_pdf_from_dump" see example in README

**Comment by sleepingcat4** [comment]
@jannisborn if I download the med, bioXivs, will I get the latest dumps or what year's dumps I will get? and also will it download all the pdfs/full-text?

**Comment by jannisborn** [comment]
Per default, you download everything from the initial release date up to today. You download metadata in JSONL format. 

To get the PDFs you need to use the wrapper post-hoc

**Comment by sleepingcat4** [comment]
@jannisborn Got an error! 

![image](https://github.com/user-attachments/assets/95d40459-b139-4174-bcec-695fe17cd14d)

Code used
```
from paperscraper.get_dumps import chemrxiv

# Download of the ChemRxiv paper dump
chemrxiv(save_path="chemrxiv_2024-26-09.jsonl")
```

**Comment by sleepingcat4** [comment]
btw what happens if it already finds the dumps?

![image](https://github.com/user-attachments/assets/63c1d2ce-32d9-4b7d-afc6-b895bddf5cf8)

Do I still download the latest dumps till today or it uses the old dumps?

```
from paperscraper.get_dumps import biorxiv, medrxiv

# Download of the ChemRxiv paper dump
biorxiv(save_path="/paper/biorxiv_2024-26-09.jsonl")
medrxiv(save_path="/paper/medrxiv_2024-26-09.jsonl")
```
btw chem is giving me error but rest works fine

**Comment by jannisborn** [comment]
Maybe chemrxiv api is down. I can't help now since I'm on vacation

**Comment by sleepingcat4** [comment]
@jannisborn that's fine, I will wait. Btw just a quick question if the code detects dumps already present does it moves forward to download the latest dumps or just uses the old dumps?

**Comment by jannisborn** [comment]
I tested the latest paperscraper version and chemrxiv dumps works fine. This is the test I ran:

```py
chemrxiv(begin_date='2024-09-25', end_date='2024-09-30', save_path='test_chemrxiv.jsonl')
```

Closing this issue, also since it should be about PubMed scraping
