### ISSUE TITLE
download abstract when pdf is not available

### ISSUE THREAD

**Issue by vmkalbskopf** [jannisborn/paperscraper#56]
Hi there!

I am using the DOI to download pdf's using `save_pdf`.
Is there a way to download the paper's abstract when the PDF is not available?

**Comment by jannisborn** [comment]
Hi @vmkalbskopf,

Currently that's not supported but it would indeed be a nice addition. I'd totally welcome a PR on this! 

Meanwhile, you can pass the title to the regular keyword search. The result should include your paper's metadata. i.e., also the abstract. It's a bit of an "abuse" to the keyword search, so not sure it works very reliably, but worth a shot. Would be curious to know whether it works, let me know

**Comment by vmkalbskopf** [comment]
When you say "abuse", do you mean that the resources I would be querying would block my IP address for excessive use?
Or do you mean that I am simply not using as it was designed?

**Comment by jannisborn** [comment]
@vmkalbskopf ah sorry just meant you use it in a way that is not intended. The regular papersraper search is intended for keywords where you want to get all papers related to a certain topic or combination of topics. In this case you are looking for a single, exact entry and I'm not sure that this will work very robustly and good! But please try and let me know

**Comment by jannisborn** [comment]
@vmkalbskopf have a look at #57 is this what you had in mind?

**Comment by vmkalbskopf** [comment]
Yeah, then I just need to extract the abstract text from the json. Thanks!
